### ISSUE TITLE
Add dns-prefetch/preload links for a site array of URLs

### ISSUE THREAD

**Issue by dleidert** [dleidert/jekyll-wgdd#2]
Add something like:

```YAML
jekyll_wgdd:
  dnsprefetch:
  - URL1
  - URL2
  preload:
  - URL3
  - URL4
```

and create links like

```HTML
<link rel=“dns-prefetch“ href=“//de.ryte.com“>
<link rel=“preconnect“ href=“//...“>
```

Check for prerender/prefetch etc. too.
